// <auto-generated />
using System;
using GeneradorComitesAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeneradorComitesAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210707133256_ComiteeMonths")]
    partial class ComiteeMonths
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeneradorComitesAPI.Models.Comitee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Comitees");
                });

            modelBuilder.Entity("GeneradorComitesAPI.Models.ComiteeMonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComiteeId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComiteeId");

                    b.ToTable("ComiteeMonths");
                });

            modelBuilder.Entity("GeneradorComitesAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BirthdayDay")
                        .HasColumnType("int");

                    b.Property<int>("BirthdayMonth")
                        .HasColumnType("int");

                    b.Property<int?>("LastComiteeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("LastComiteeId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("GeneradorComitesAPI.Models.PersonsComitee", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("ComiteeId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "ComiteeId");

                    b.HasIndex("ComiteeId");

                    b.ToTable("PersonsComitees");
                });

            modelBuilder.Entity("GeneradorComitesAPI.Models.ComiteeMonth", b =>
                {
                    b.HasOne("GeneradorComitesAPI.Models.Comitee", "Comitee")
                        .WithMany()
                        .HasForeignKey("ComiteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comitee");
                });

            modelBuilder.Entity("GeneradorComitesAPI.Models.Person", b =>
                {
                    b.HasOne("GeneradorComitesAPI.Models.Comitee", "LastComitee")
                        .WithMany()
                        .HasForeignKey("LastComiteeId");

                    b.Navigation("LastComitee");
                });

            modelBuilder.Entity("GeneradorComitesAPI.Models.PersonsComitee", b =>
                {
                    b.HasOne("GeneradorComitesAPI.Models.Comitee", "Comitee")
                        .WithMany()
                        .HasForeignKey("ComiteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeneradorComitesAPI.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comitee");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
